INSERT INTO OwnerPreferences (Owner_ID, Preferred_Breed, Preferred_Size, Preferred_Gender, Max_Age, Vaccination_Required, Good_With_Kids_Required, Potty_Trained_Required, Good_With_Dogs_Required) VALUES
(1, 'Labrador', 'Medium', 'M', 5, TRUE, TRUE, TRUE, TRUE),
(2, 'Poodle', 'Small', 'F', 8, FALSE, FALSE, TRUE, TRUE),
(3, 'German Shepherd', 'Large', 'M', 7, TRUE, TRUE, FALSE, TRUE),
(4, 'Beagle', 'Small', 'M', 4, FALSE, TRUE, TRUE, FALSE),
(5, 'Bulldog', 'Medium', 'F', 6, FALSE, TRUE, FALSE, TRUE),
(6, 'Golden Retriever', 'Large', 'M', 3, TRUE, FALSE, TRUE, TRUE),
(7, 'Boxer', 'Large', 'F', 8, FALSE, TRUE, TRUE, FALSE),
(8, 'Dachshund', 'Small', 'M', 5, TRUE, TRUE, FALSE, TRUE),
(9, 'Chihuahua', 'Small', 'F', 2, FALSE, FALSE, TRUE, FALSE),
(10, 'Shih Tzu', 'Small', 'M', 6, TRUE, FALSE, FALSE, TRUE),
(11, 'Pomeranian', 'Small', 'F', 3, TRUE, TRUE, TRUE, TRUE),
(12, 'Siberian Husky', 'Large', 'M', 4, FALSE, FALSE, FALSE, TRUE),
(13, 'Dalmatian', 'Medium', 'F', 7, TRUE, FALSE, TRUE, TRUE),
(14, 'Corgi', 'Medium', 'M', 5, TRUE, TRUE, TRUE, FALSE),
(15, 'Rottweiler', 'Large', 'F', 8, TRUE, TRUE, TRUE, FALSE),
(16, 'Great Dane', 'Large', 'M', 3, FALSE, FALSE, TRUE, TRUE),
(17, 'Collie', 'Medium', 'F', 6, FALSE, FALSE, TRUE, FALSE),
(18, 'Shiba Inu', 'Medium', 'M', 4, TRUE, TRUE, TRUE, TRUE),
(19, 'Doberman Pinscher', 'Large', 'F', 5, TRUE, FALSE, FALSE, TRUE),
(20, 'Shetland Sheepdog', 'Medium', 'M', 7, FALSE, FALSE, TRUE, FALSE),
(21, 'Pug', 'Small', 'F', 2, FALSE, TRUE, TRUE, TRUE),
(22, 'Yorkshire Terrier', 'Small', 'M', 4, TRUE, TRUE, FALSE, TRUE),
(23, 'Australian Shepherd', 'Medium', 'F', 6, FALSE, TRUE, FALSE, FALSE),
(24, 'Cavalier King Charles Spaniel', 'Small', 'M', 3, FALSE, TRUE, TRUE, FALSE),
(25, 'Bernese Mountain Dog', 'Large', 'F', 5, TRUE, FALSE, TRUE, FALSE),
(26, 'Maltese', 'Small', 'M', 2, TRUE, TRUE, FALSE, FALSE),
(27, 'Basset Hound', 'Medium', 'F', 8, TRUE, FALSE, FALSE, FALSE),
(28, 'Border Collie', 'Medium', 'M', 4, FALSE, TRUE, TRUE, FALSE),
(29, 'Staffordshire Bull Terrier', 'Medium', 'F', 5, FALSE, FALSE, TRUE, TRUE),
(30, 'Chow Chow', 'Medium', 'M', 6, TRUE, FALSE, TRUE, FALSE),
(31, 'Akita', 'Large', 'F', 3, TRUE, TRUE, FALSE, TRUE),
(32, 'Poodle', 'Small', 'M', 6, TRUE, TRUE, TRUE, TRUE),
(33, 'French Bulldog', 'Small', 'F', 4, FALSE, TRUE, TRUE, TRUE),
(34, 'English Springer Spaniel', 'Medium', 'M', 6, FALSE, TRUE, FALSE, TRUE),
(35, 'Bichon Frise', 'Small', 'F', 3, TRUE, FALSE, TRUE, TRUE),
(36, 'Bullmastiff', 'Large', 'M', 8, TRUE, FALSE, FALSE, TRUE),
(37, 'Schnauzer', 'Medium', 'F', 5, TRUE, FALSE, TRUE, TRUE),
(38, 'Shiba Inu', 'Medium', 'M', 4, TRUE, FALSE, FALSE, TRUE),
(39, 'Beagle', 'Small', 'F', 6, FALSE, TRUE, TRUE, FALSE),
(40, 'Labrador', 'Medium', 'M', 3, TRUE, FALSE, FALSE, TRUE),
(41, 'Pug', 'Small', 'F', 5, FALSE, TRUE, FALSE, TRUE),
(42, 'Dalmatian', 'Medium', 'M', 8, FALSE, TRUE, FALSE, FALSE),
(43, 'Siberian Husky', 'Large', 'F', 4, TRUE, TRUE, FALSE, FALSE),
(44, 'Golden Retriever', 'Large', 'M', 7, TRUE, TRUE, FALSE, TRUE),
(45, 'Chihuahua', 'Small', 'F', 2, FALSE, FALSE, TRUE, FALSE),
(46, 'Poodle', 'Small', 'M', 6, TRUE, FALSE, TRUE, TRUE),
(47, 'Bulldog', 'Medium', 'F', 5, TRUE, TRUE, TRUE, FALSE),
(48, 'German Shepherd', 'Large', 'M', 4, FALSE, TRUE, FALSE, FALSE),
(49, 'Boxer', 'Large', 'F', 8, FALSE, TRUE, FALSE, TRUE),
(50, 'Rottweiler', 'Large', 'M', 3, FALSE, TRUE, TRUE, FALSE),
(51, 'Collie', 'Medium', 'F', 7, FALSE, TRUE, TRUE, FALSE),
(52, 'Shetland Sheepdog', 'Medium', 'M', 5, TRUE, TRUE, FALSE, TRUE),
(53, 'Pug', 'Small', 'F', 3, FALSE, FALSE, FALSE, TRUE),
(54, 'Shiba Inu', 'Medium', 'M', 4, TRUE, FALSE, TRUE, TRUE),
(55, 'Doberman Pinscher', 'Large', 'F', 5, FALSE, FALSE, TRUE, FALSE),
(56, 'Shetland Sheepdog', 'Medium', 'M', 7, TRUE, TRUE, TRUE, FALSE),
(57, 'Chihuahua', 'Small', 'F', 2, TRUE, FALSE, FALSE, TRUE),
(58, 'Siberian Husky', 'Large', 'M', 4, FALSE, TRUE, FALSE, TRUE),
(59, 'Dalmatian', 'Medium', 'F', 6, FALSE, TRUE, TRUE, FALSE),
(60, 'Golden Retriever', 'Large', 'M', 3, TRUE, TRUE, FALSE, TRUE),
(61, 'Corgi', 'Medium', 'F', 5, FALSE, FALSE, TRUE, FALSE),
(62, 'Rottweiler', 'Large', 'M', 8, TRUE, TRUE, TRUE, FALSE),
(63, 'Great Dane', 'Large', 'F', 4, FALSE, TRUE, TRUE, FALSE),
(64, 'Collie', 'Medium', 'M', 6, FALSE, TRUE, TRUE, TRUE),
(65, 'Shiba Inu', 'Medium', 'F', 3, TRUE, FALSE, FALSE, TRUE),
(66, 'Cavalier King Charles Spaniel', 'Small', 'M', 2, TRUE, TRUE, FALSE, TRUE),
(67, 'Bernese Mountain Dog', 'Large', 'F', 5, TRUE, FALSE, TRUE, FALSE),
(68, 'Maltese', 'Small', 'M', 2, TRUE, TRUE, FALSE, TRUE),
(69, 'Basset Hound', 'Medium', 'F', 7, TRUE, FALSE, FALSE, TRUE),
(70, 'Border Collie', 'Medium', 'M', 4, TRUE, FALSE, TRUE, FALSE),
(71, 'Staffordshire Bull Terrier', 'Medium', 'F', 5, TRUE, TRUE, TRUE, TRUE),
(72, 'Chow Chow', 'Medium', 'M', 6, FALSE, FALSE, TRUE, FALSE),
(73, 'Akita', 'Large', 'F', 3, FALSE, TRUE, FALSE, TRUE),
(74, 'Shih Tzu', 'Small', 'M', 5, FALSE, TRUE, FALSE, TRUE),
(75, 'Pomeranian', 'Small', 'F', 2, FALSE, FALSE, TRUE, FALSE),
(76, 'French Bulldog', 'Small', 'M', 4, TRUE, FALSE, FALSE, FALSE),
(77, 'English Springer Spaniel', 'Medium', 'F', 6, TRUE, FALSE, TRUE, TRUE),
(78, 'Bichon Frise', 'Small', 'M', 3, TRUE, TRUE, FALSE, FALSE),
(79, 'Bullmastiff', 'Large', 'F', 8, TRUE, FALSE, FALSE, FALSE),
(80, 'Schnauzer', 'Medium', 'M', 5, TRUE, FALSE, TRUE, TRUE),
(81, 'Poodle', 'Small', 'F', 2, TRUE, TRUE, TRUE, TRUE),
(82, 'Shiba Inu', 'Medium', 'M', 4, TRUE, TRUE, FALSE, FALSE),
(83, 'Beagle', 'Small', 'F', 6, FALSE, FALSE, TRUE, TRUE),
(84, 'Labrador', 'Medium', 'M', 3, TRUE, FALSE, FALSE, TRUE),
(85, 'Pug', 'Small', 'F', 5, FALSE, TRUE, FALSE, TRUE),
(86, 'Dalmatian', 'Medium', 'M', 8, FALSE, TRUE, FALSE, FALSE),
(87, 'Siberian Husky', 'Large', 'F', 4, TRUE, TRUE, FALSE, FALSE),
(88, 'Golden Retriever', 'Large', 'M', 7, TRUE, TRUE, FALSE, TRUE),
(89, 'Chihuahua', 'Small', 'F', 2, FALSE, FALSE, TRUE, FALSE),
(90, 'Poodle', 'Small', 'M', 6, TRUE, TRUE, TRUE, TRUE),
(91, 'Bulldog', 'Medium', 'F', 5, FALSE, TRUE, FALSE, TRUE),
(92, 'German Shepherd', 'Large', 'M', 4, FALSE, TRUE, FALSE, FALSE),
(93, 'Boxer', 'Large', 'F', 8, FALSE, TRUE, FALSE, TRUE),
(94, 'Rottweiler', 'Large', 'M', 3, FALSE, TRUE, TRUE, FALSE),
(95, 'Collie', 'Medium', 'F', 7, FALSE, TRUE, TRUE, FALSE),
(96, 'Shetland Sheepdog', 'Medium', 'M', 5, TRUE, TRUE, FALSE, TRUE),
(97, 'English Springer Spaniel', 'Small', 'M', 11, FALSE, TRUE, FALSE, TRUE),
(98, 'Mini Pin', 'Small', 'M', 12, FALSE, TRUE, FALSE, TRUE),
(99, 'Husky', 'Medium', 'F', 13, FALSE, TRUE, FALSE, TRUE),
(100, 'Chow Chow', 'Small', 'F', 11, FALSE, TRUE, FALSE, TRUE);

