INSERT INTO Pets (Pet_ID, Name, Breed, Color, Age, Size, Gender, Weight, Shelter_id)
VALUES
(1, 'BK', 'Bullmastiff', 'Brindle', 'Young', 'Extra Large', 'M', NULL, 1),
(2, 'Sammy', 'Bullmastiff', 'Brindle', 'Adult', 'Large', 'M', NULL, 1),
(3, 'Tuney', 'Bullmastiff', 'Brindle', 'Young', 'Extra Large', 'F', NULL, 1),
(4, 'Xavier', 'Bullmastiff', 'Brindle', 'Adult', 'Extra Large', 'M', NULL, 1),
(5, 'Midge Maisel', 'Terrier/Hound Mix', 'Brown/White', 'Adult', 'Medium', 'F', 40, 2),
(6, 'Rocky', 'Boxer/Labrador Retriever Mix', 'White', 'Adult', 'Medium', 'M', NULL, 2),
(7, 'Boba', 'Mixed Breed', 'Black/White', 'Adult', 'Large', 'F', NULL, 3),
(8, 'Virgo', 'Mixed Breed', 'Black', 'Senior', 'Large', 'F', NULL, 3),
(9, 'Fed-Ex', 'Mixed Breed', 'Brown', 'Young', 'Large', 'M', NULL, 3),
(10, 'Pop Tart', 'Doberman Pinscher/Pit Bull Terrier Mix', 'Brown', 'Adult', 'Large', 'F', NULL, 4),
(11, 'Potter', 'Staffordshire Bull Terrier/Black Ladrador Retriever', 'Black', 'Adult', 'Medium', 'M', NULL, 4),
(12, 'Zelma', 'Chihuahua Mix', 'Brown', 'Senior', 'Small', 'F', NULL, 5),
(13, 'Bogey', 'Basset Hound/Beagle Mix', 'Red/White', 'Adult', 'Medium', 'M', NULL, 6),
(14, 'Ollie', 'Basset Hound', 'Brown/Black/White', 'Adult', 'Medium', 'M', NULL, 6),
(15, 'Tucker', 'Basset Hound', 'Red/White', 'Senior', 'Medium', 'M', NULL, 6),
(16, 'Mocha', 'Pointer/Spaniel Mix', 'Brown/White', 'Adult', 'Medium', 'F', NULL, 7),
(17, 'Clark', 'English Springer Spaniel', 'Black/White', 'Adult', 'Medium', 'M', 45, 8),
(18, 'Finn', 'English Springer Spaniel', 'Brown/White', 'Adult', 'Medium', 'M', NULL, 8),
(19, 'Myers', 'English Springer Spaniel', 'Brown', 'Adult', 'Large', 'M', 58, 8),
(20, 'Oreo', 'English Springer Spaniel', 'Black/White', 'Young', 'Medium', 'M', 45, 8),
(21, 'Panada', 'English Springer Spaniel', 'Black/White', 'Young', 'Medium', 'M', 52, 8),
(22, 'Rigby', 'English Springer Spaniel', 'Brown/White', 'Adult', 'Medium', 'M', NULL, 8),
(23, 'Rocky', 'English Springer Spaniel', 'Black/White', 'Adult', 'Medium', 'M', 41, 8),
(24, 'Weaver', 'English Springer Spaniel', 'Brown/White', 'Senior', 'Medium', 'M', 40, 8),
(25, 'Benny', 'Shar-Pei/Labrador Retriever Mix', 'Orange', 'Adult', 'Large', 'M', 54, 9),
(26, 'Buck', 'Pit Bull Terrier', 'Brown', 'Young', 'Medium', 'M', NULL, 10),
(27, 'Louie', 'Labrador Retriever Mix', 'Brown/Black', 'Young', 'Small', 'M', NULL, 10),
(28, 'Maisie', 'Schnauzer Mix', 'Black/White', 'Senior', 'Small', 'F', NULL, 10),
(29, 'Mello', 'Labrador Retriever/Poodle Mix', 'Cream', 'Young', 'Medium', 'M', NULL, 10),
(30, 'Mozilla', 'Saluki', 'Brown/Black/White', 'Young', 'Medium', 'M', NULL, 10),
(31, 'Athena', 'Australian Shepherd/Labrador Retriever Mix', 'Black/White', 'Adult', 'Large', 'F', 65, 11),
(32, 'Blu', 'American Staffordshire Terrier Mix', 'Gray', 'Adult', 'Medium', 'F', NULL, 11),
(33, 'Butters', 'American Staffordshire Terrier', 'Brown/White', 'Adult', 'Medium', 'M', 50, 11),
(34, 'Copper', 'Retriever/Labrador Retriever Mix', 'Brown', 'Adult', 'Large', 'M', NULL, 11),
(35, 'Dawson', 'Shepherd/Black Mouth Cur Mix', 'Golden', 'Adult', 'Large', 'M', 60, 11),
(36, 'Garnet', 'American Staffordshire Terrier/Boxer Mix', 'Yellow', 'Young', 'Medium', 'F', NULL, 11),
(37, 'Kenny', 'Boxer/Shepherd Mix', 'Brown', 'Young', 'Medium', 'M', NULL, 11),
(38, 'Olive', 'Staffordshire Bull Terrier', 'Black/White', 'Adult', 'Medium', 'F', NULL, 11),
(39, 'Pink', 'American Staffordshire Terrier Mix', 'Golden/White', 'Adult', 'Medium', 'F', 28, 11),
(40, 'Puddin', 'Black Labrador Retriever/Pit Bull Terrier Mix', 'Black', 'Young', 'Medium', 'M', 50, 11),
(41, 'Sally', 'American Staffordshire Terrier Mix', 'Gray', 'Adult', 'Medium', 'F', NULL, 11),
(42, 'Shiloh', 'Hound/Beagle Mix', 'Brown/Black/White', 'Young', 'Medium', 'F', NULL, 11),
(43, 'Sunny', 'Chihuahua/Terrier Mix', 'Red', 'Young', 'Small', 'F', 18, 11),
(44, 'Beckett', 'American Staffordshire Terrier/Pointer Mix', 'Brown/Black/White', 'Adult', 'Medium', 'M', NULL, 12),
(45, 'Charlie', 'Chihuahua Mix', 'Brown', 'Adult', 'Small', 'F', NULL, 12),
(46, 'Chico', 'Chihuahua Mix', 'Black', 'Adult', 'Small', 'M', NULL, 12),
(47, 'Ginger', 'Chihuahua/Norwegian Elkhound Mix', 'Sable', 'Adult', 'Small', 'F', 14, 12),
(48, 'Jasper', 'Terrier Mix', 'Black', 'Adult', 'Small', 'M', NULL, 12),
(49, 'Kinder', 'Pit Bull Terrier Mix', 'Brown/Gray', 'Adult', 'Large', 'M', 65, 12),
(50, 'Pooh Bear', 'Chihuahua', 'Tan', 'Adult', 'Small', 'M', NULL, 12),
(51, 'Sally', 'Parson Russell Terrier/Cattle Dog Mix', 'Black', 'Young', 'Medium', 'F', NULL, 12),
(52, 'Tilly', 'Pit Bull Terrier Mix', 'Black', 'Young', 'Large', 'F', 50, 12),
(53, 'Tyler', 'Pit Bull Terrier Mix', 'Brindle', 'Puppy', 'Medium', 'M', NULL, 12),
(54, 'Ferb', 'Rat Terrier/Hound Mix', 'Brown/Black/White', 'Senior', 'Medium', 'M', 40, 13),
(55, 'Flash', 'Feist/Jack Russell Terrier Mix', 'Brown/Black/White', 'Senior', 'Medium', 'F', NULL, 13),
(56, 'Fred', 'Fiest Mix', 'Brown/Black/White', 'Senior', 'Medium', 'M', NULL, 13),
(57, 'Lady Bird', 'Jack Russell Terrier/Beagle Mix', 'Brown/White', 'Senior', 'Medium', 'F', NULL, 13),
(58, 'Walker', 'Rat Terrier Mix', 'Brown/Black/White', 'Adult', 'Small', 'M', NULL, 13),
(59, 'Queen', 'Siberian Husky', 'Black/White', 'Adult', 'Medium', 'F', NULL, 14),
(60, 'Faith', 'Shar-Pei', 'Gray', 'Senior', 'Medium', 'F', NULL, 15),
(61, 'Freddy', 'Plott Hound Mix', 'Brindle', 'Adult', 'Medium', 'M', NULL, 15),
(62, 'Mr P', 'Pit Bull Terrier Mix', 'Brown/White', 'Adult', 'Large', 'M', NULL, 15),
(63, 'Poppy', 'Caucasian Sheepdog/Caucasiam Ovtcharka', 'Black/White', 'Adult', 'Large', 'F', NULL, 15),
(64, 'Rocky', 'Yorkshire Terrier', 'Blue/Tan', 'Senior', 'Small', 'M', NULL, 15),
(65, 'Skunay', 'Beagle/Cardigan Welsh Corgi Mix', 'Brown', 'Senior', 'Small', 'M', NULL, 15),
(66, 'Daisy', 'Miniature Daschshund/Chihuahua Mix', 'Brown', 'Adult', 'Small', 'F', 25, 16),
(67, 'Groot', 'Chuhuahua/Jack Russell Terrier Mix', 'Brown', 'Adult', 'Small', 'M', 22, 16),
(68, 'Midge', 'Jack Russell Terrier', 'Brown/White', 'Adult', 'Small', 'F', 9, 16),
(69, 'Oscar', 'Beagle/Jack Russell Terrier', 'Brown/White', 'Senior', 'Small', 'M', 20, 16),
(70, 'Cannoli', 'Jack Russell Terrier', 'Brown/White', 'Adult', 'Small', 'M', 18, 16),
(71, 'Dreamsicle', 'Miniature Poodle', 'Apricot/Beige', 'Adult', 'Small', 'M', 17, 16),
(72, 'Lightning', 'Miniature Schnauzer/Terrier Mix', 'Black/White', 'Adult', 'Small', 'M', 12, 16),
(73, 'Hayden', 'German Shepherd/Akita Mix', 'Black/White', 'Puppy', 'Medium', 'M', 40, 17),
(74, 'Babygirl', 'Labrador Retriever/Pointer Mix', 'Black/White', 'Adult', 'Medium', 'F', 35, 18),
(75, 'Henny Cookie', 'Border Collie/Labrador Retriever Mix', 'Brown/White', 'Adult', 'Large', 'M', 77, 18),
(76, 'Oreo Cookie', 'Border Collie/Labrador Retriever Mix', 'Black/White', 'Adult', 'Large', 'M', 55, 18),
(77, 'Ash', 'Standard Poodle', 'Black', 'Adult', 'Medium', 'M', NULL, 19),
(78, 'Finley', 'Standard Poodle', 'Beige', 'Adult', 'Medium', 'F', 41, 19),
(79, 'Jess', 'Hound/Labrador Retriever Mix', 'Brown/Black/White', 'Young', 'Medium', 'F', NULL, 19),
(80, 'Randy', 'Wirehaired Terrier Mix', 'Beige', 'Adult', 'Small', 'M', NULL, 19),
(81, 'Harley', 'German Spitz', 'Black', 'Adult', 'Medium', 'M', 33, 19),
(82, 'Cookie', 'Japanese Chin', 'Black/White', 'Senior', 'Small', 'M', NULL, 19),
(83, 'Berkeley', 'Labrador Retriever/Yellow Labrador Retriever Mix', 'Yellow', 'Adult', 'Large', 'M', NULL, 20),
(84, 'Bristol', 'Beagle/Terrier Mix', 'White/Brindle', 'Young', 'Medium', 'F', 38, 20),
(85, 'Bruno', 'Boxer/Hounf Mix', 'Brown/White', 'Adult', 'Large', 'M', 60, 20),
(86, 'Chika', 'Chihuahua Mix', 'Beige', 'Adult', 'Small', 'F', 5, 20),
(87, 'Dex', 'Labrador Retriever/Black Labrador Retriever Mix', 'Black', 'Adult', 'Large', 'M', 55, 20),
(88, 'Duncan Ladd', 'German Shepherd Dog Mix', 'Black', 'Young', 'Large', 'M', 67, 20),
(89, 'Emmett', 'Terrier Mix', 'Brindle', 'Adult', 'Large', 'M', 55, 20),
(90, 'Freya', 'Shepherd Mix', 'Yellow/Cream', 'Adult', 'Medium', 'F', 51, 20),
(91, 'Gabbie', 'Irish Setter/Hound Mix', 'Red/White', 'Adult', 'Large', 'F', 55, 20),
(92, 'Gracie Sage', 'Terrier Mix', 'Black/White', 'Adult', 'Large', 'F', NULL, 20),
(93, 'Indy', 'Shepherd Mix', 'Yellow', 'Adult', 'Large', 'M', NULL, 20),
(94, 'Leo Henry', 'American Bulldog Mix', 'Yellow', 'Adult', 'Medium', 'M', 50, 20),
(95, 'Macy Jean', 'American Staffordshire Terrier Mix', 'Black/White', 'Adult', 'Large', 'F', 65, 20),
(96, 'Puzzle', 'Plott Gound/Boxer Mix', 'Brindle', 'Adult', 'Large', 'M', 75, 20),
(97, 'Sarge', 'Husky Mix', 'White/Gray', 'Senior', 'Extra Large', 'M', 120, 20),
(98, 'Sieva', 'Black Mouth Cur/Shepherd Mix', 'Brown', 'Adult', 'Large', 'F', 61, 20),
(99, 'Winston', 'Beagle/Terrier Mix', 'Brown/Black/White', 'Senior', 'Medium', 'M', 34, 20),
(100, 'Zee Zee', 'Boxer/American Bulldog Mix', 'White', 'Adult', 'Medium', 'F', NULL, 20);