INSERT INTO Shelters (Shelter_ID, Shelter, Location, Website)
VALUES
(1, 'American Bullmastiff Rescue', 'Atlanta, GA', 'https://bullmastiff.us/rescue/'),
(2, 'Animal Action Rescue', 'Atlanta, GA', 'https://www.facebook.com/p/Animal-Action-Rescue-Inc-100064580925718/'),
(3, 'AthensPets', 'Athens, GA', 'https://www.accgov.com/animalservices'),
(4, 'Atlanta Animal Rescue Friends Inc', 'Atlanta, GA', 'https://www.aarfatlanta.org/'),
(5, 'Atlanta Canine Adoption Project', 'Monticello, GA', 'https://www.adoptdont.shop/o/1137522/atlanta-canine-adoption-project'),
(6, 'Basset Hound Rescue of Georgia', 'Fayetteville, GA', 'http://www.bhrg.org/'),
(7, 'BullyWag', 'Douglasville, GA', 'https://www.bullywaginc.org/'),
(8, 'English Springer Rescue America', 'Atlanta, GA', 'https://www.springerrescue.org/'),
(9, 'Friends of Shelter Animals for Cobb County', 'Atlanta, GA', 'https://www.facebook.com/groups/110442035657408/'),
(10, 'Fulton County Animal Services', 'Atlanta, GA', 'https://fultonanimalservices.com/'),
(11, 'Ginny Millner Rescue Group', 'Atlanta, GA', 'https://www.facebook.com/groups/220500877968683/'),
(12, 'Laskey''s Luck Ones/Volunteers', 'Atlanta, GA', 'https://llovorg.wordpress.com/'),
(13, 'Little Nuggets Rescue', 'Atlanta, GA', 'http://www.littlenuggetsrescue.com/contact.html'),
(14, 'Releashed Rescue', 'Cumming, GA', 'https://www.releashedrescue.com/'),
(15, 'Rescue Angels of GA', 'Alpharetta, GA', 'https://angelsrescue.org/'),
(16, 'Royal Potcake Resucue', 'Tucker, GA', 'https://www.facebook.com/royal.potcake.rescue/'),
(17, 'Wags and Wiggles Dog Rescue', 'Cumming, GA', 'https://www.wagsandwigglesdogrescue.org/'),
(18, 'We Are Rescue', 'Woodstock, GA', 'http://www.adoptapet.com/wearerescuega'),
(19, 'Wet Noses Animal Rescue', 'Blue Ridge, GA', 'https://wetnosesanimalrescue.org/'),
(20, 'You Lucky Dog Rescue', 'Alpharetta, GA', 'http://youluckydogrescue.org/');
